---

services:
  subservice:
    container_name: sub-service
    build:
      context: ./
      dockerfile: ./build/sub_service/dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    ports: 
      - "${DOCKER_SERVICE_PORT}:${LISTEN_PORT}"
    
  postgres:
    image: postgres:16-alpine
    container_name: subservice-db
    environment:
      POSTGRES_DB: ${PSQL_NAME}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_PORT: ${PSQL_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PSQL_USER} -d ${PSQL_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "${DOCKER_PSQL_PORT}:${PSQL_PORT}"

  migration:
    container_name: subservice-migrator
    build:
      context: ./
      dockerfile: ./build/migrator/dockerfile
    command:
      ["goose", "-dir", "migrations", "postgres", "host=${PSQL_HOST} port=${PSQL_PORT} dbname=${PSQL_NAME} user=${PSQL_USER} password=${PSQL_PASSWORD} sslmode=disable", "up"]
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local